In [20]:
import pandas as pd
%load_ext sql
%sql sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [21]:
##--11. Products tablosundaki CategoryID’leri var ama numara seklinde bu katagorileri isimleri nelerdir?
%sql SELECT * FROM Products LEFT JOIN Categories on Products.CategoryID = Categories.CategoryID;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30, 7, 'Produce', 'Dried fruit and bean curd'),
 (8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97, 6, 'Meat/Poultry', 'Prepared meats'),
 (10, 'Ikura', 4, 8, '12 - 200 ml jars', 31, 8, 'Seafood', 'Seaweed and fish'),
 (11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21, 4, 'Dairy Products', 'Cheeses'),
 (12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38, 4, 'Dairy Products', 'Cheeses'),
 (13, 'Konbu', 6, 8, '2 kg box', 6, 8, 'Seafood', 'Seaweed and fish'),
 (14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23, 7, 'Produce', 'Dried fruit and bean curd'),
 (15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39, 6, 'Meat/Poultry', 'Prepared meats'),
 (18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62, 8, 'Seafood', 'Seaweed and fish'),
 (19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 43, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45, 7, 'Produce', 'Dried fruit and bean curd'),
 (29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123, 6, 'Meat/Poultry', 'Prepared meats'),
 (30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25, 8, 'Seafood', 'Seaweed and fish'),
 (31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 435, 4, 'Dairy Products', 'Cheeses'),
 (32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32, 4, 'Dairy Products', 'Cheeses'),
 (33, 'Geitost', 15, 4, '500 g', 43, 4, 'Dairy Products', 'Cheeses'),
 (34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19, 8, 'Seafood', 'Seaweed and fish'),
 (37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26, 8, 'Seafood', 'Seaweed and fish'),
 (38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 43, 8, 'Seafood', 'Seaweed and fish'),
 (41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 23, 8, 'Seafood', 'Seaweed and fish'),
 (42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (45, 'Røgede sild', 21, 8, '1k pkg.', 43, 8, 'Seafood', 'Seaweed and fish'),
 (46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12, 8, 'Seafood', 'Seaweed and fish'),
 (47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (48, 'Chocolade', 22, 3, '10 pkgs.', 27, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53, 7, 'Produce', 'Dried fruit and bean curd'),
 (52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (53, 'Perth Pasties', 24, 6, '48 pieces', 32, 6, 'Meat/Poultry', 'Prepared meats'),
 (54, 'Tourtière', 25, 6, '16 pies', 16, 6, 'Meat/Poultry', 'Prepared meats'),
 (55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24, 6, 'Meat/Poultry', 'Prepared meats'),
 (56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 43, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13, 8, 'Seafood', 'Seaweed and fish'),
 (59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55, 4, 'Dairy Products', 'Cheeses'),
 (60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34, 4, 'Dairy Products', 'Cheeses'),
 (61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (62, 'Tarte au sucre', 29, 3, '48 pies', 49, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 45, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36, 4, 'Dairy Products', 'Cheeses'),
 (70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21, 4, 'Dairy Products', 'Cheeses'),
 (72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34, 4, 'Dairy Products', 'Cheeses'),
 (73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15, 8, 'Seafood', 'Seaweed and fish'),
 (74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10, 7, 'Produce', 'Dried fruit and bean curd'),
 (75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 27, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (76, 'Lakkalikööri', 23, 1, '500 ml', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings')]

In [22]:
#12. beverages ürün kategorisindeki ürünlerin fiyat ortalaması nedir?
%sql SELECT avg(Price) FROM Products LEFT JOIN Categories on Products.CategoryID = categories.CategoryID  where CategoryName='Beverages'

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(42.75,)]

In [23]:
#13. USA'de yaşayan müşterilerin kazandırdığı toplam kazancı bulunuz.
%sql SELECT SUM(p.Price) FROM Orders o LEFT JOIN OrderDetails od on o.OrderID = od.OrderID  LEFT JOIN Products p on od.ProductID = p.ProductID  LEFT JOIN Customers cu on o.CustomerID = cu.CustomerID where cu.Country = 'USA';

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(3762,)]

In [24]:
##14. Products tablosundaki CategoryID'lerin isimlerini bulunuz ve sonrasında kategori başına ortalama ürün fiyatını gösteriniz.
%sql SELECT AVG(Price), CategoryName FROM Products  LEFT JOIN Categories on Products.CategoryID = Categories.CategoryID GROUP BY CategoryName;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(42.75, 'Beverages'),
 (28.25, 'Condiments'),
 (33.76923076923077, 'Confections'),
 (74.9, 'Dairy Products'),
 (23.571428571428573, 'Grains/Cereals'),
 (55.166666666666664, 'Meat/Poultry'),
 (32.2, 'Produce'),
 (26.5, 'Seafood')]

In [25]:
#15. Çalışanları (EmployeeID) isimleri ile birlikte yaptıkları toplam satışlara göre sıralayınız.
%sql SELECT em.FirstName, SUM(p.Price) toplam_satis  FROM Orders o  LEFT JOIN OrderDetails od on o.OrderID = od.OrderID  LEFT JOIN Products p on od.ProductID = p.ProductID  LEFT JOIN Employees em on o.EmployeeID = em.EmployeeID  GROUP BY o.EmployeeID  ORDER BY toplam_satis DESC;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[('Margaret', 5515),
 ('Nancy', 4353),
 ('Janet', 3048),
 ('Michael', 2981),
 ('Laura', 2380),
 ('Robert', 1852),
 ('Andrew', 1550),
 ('Steven', 1408),
 ('Anne', 520)]

In [27]:
#16. Germany'dan verilen siparişlerin kategorilerine göre ortalama fiyatları nelerdir?
%sql SELECT ca.CategoryName ,avg(p.price)  FROM Orders o LEFT JOIN OrderDetails od on o.OrderID = od.OrderID LEFT JOIN Products p on od.ProductID = p.ProductID LEFT JOIN Categories ca on p.CategoryID = ca.CategoryID LEFT JOIN Customers cu on o.CustomerID = cu.CustomerID WHERE cu.Country = 'Germany' GROUP BY CategoryName;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[('Beverages', 20.5),
 ('Condiments', 34.0),
 ('Confections', 40.0),
 ('Dairy Products', 151.64705882352942),
 ('Grains/Cereals', 22.142857142857142),
 ('Meat/Poultry', 30.2),
 ('Produce', 30.75),
 ('Seafood', 27.09090909090909)]

In [28]:
#17. Almanya ya da USA'den verilen siparişlerin kategorilerine göre ortalama fiyatları nelerdir?
%sql SELECT ca.CategoryName, AVG(p.Price)  FROM Orders o LEFT JOIN OrderDetails od on o.OrderId = od.OrderId LEFT JOIN Products p on od.ProductID = p.ProductID  LEFT JOIN Categories ca on p.CategoryID = ca.CategoryID LEFT JOIN Customers cu on o.CustomerID = cu.CustomerID WHERE cu.Country = 'Germany' OR cu.Country = 'USA' GROUP BY CategoryName;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[('Beverages', 29.88888888888889),
 ('Condiments', 34.72727272727273),
 ('Confections', 39.92307692307692),
 ('Dairy Products', 131.75862068965517),
 ('Grains/Cereals', 29.846153846153847),
 ('Meat/Poultry', 46.75),
 ('Produce', 28.625),
 ('Seafood', 25.6)]

In [29]:
 ##18. Haziran Temmuz Ağustos aylarında verilen siparişlerin ortalama fiyatı nedir?
%sql SELECT AVG(Products.Price) FROM Products LEFT JOIN OrderDetails on OrderDetails.ProductID = products.ProductID LEFT JOIN Orders on OrderDetails.OrderID = Orders.OrderID WHERE OrderDate like '%07%' or OrderDate like '%08%' or OrderDate like '%09%';

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(39.71891891891892,)]

In [30]:
#19. Müşterilerin 1997 yılına ait siparişlerinin maksimum miktarlarını bulup müşterilerin isimleri ile birlikte büyükten küçüğe sıralayınız.
%sql SELECT CustomerName, MAX(Price) maks FROM Products LEFT JOIN OrderDetails on Products.ProductID = OrderDetails.ProductID LEFT JOIN Orders on OrderDetails.OrderID = Orders.OrderID LEFT JOIN Customers on Customers.CustomerID = Orders.CustomerID WHERE OrderDate like '%1997%' GROUP BY CustomerName ORDER BY maks DESC;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[('Gourmet Lanchonetes', 435),
 ('Simons bistro', 263),
 ('Mère Paillarde', 263),
 ('Save-a-lot Markets', 123),
 ('Eastern Connection', 123),
 ('Wellington Importadora', 97),
 ('Ernst Handel', 55),
 ('Bottom-Dollar Marketse', 55),
 ("La maison d'Asie", 49),
 ('Folies gourmandes', 49),
 ('Reggiani Caseifici', 45),
 ('Queen Cozinha', 45),
 ('Wartian Herkku', 43),
 ('Toms Spezialitäten', 43),
 ('Rattlesnake Canyon Grocery', 43),
 ('Que Delícia', 43),
 ('QUICK-Stop', 43),
 ('Old World Delicatessen', 43),
 ('Hungry Owl All-Night Grocers', 43),
 ('Hungry Coyote Import Store', 43),
 ('Familia Arquibaldo', 43),
 ('Princesa Isabel Vinhoss', 38),
 ('Galería del gastrónomo', 38),
 ('Blondel père et fils', 38),
 ('Richter Supermarkt', 36),
 ('Ottilies Käseladen', 36),
 ('Consolidated Holdings', 34),
 ('Split Rail Beer & Ale', 31),
 ('Magazzini Alimentari Riuniti', 31),
 ('Franchi S.p.A.', 31),
 ('Piccolo und mehr', 23),
 ('Océano Atlántico Ltda.', 23),
 ('Folk och fä HB', 21),
 ('LINO-Delicateses', 10)]

In [31]:
#20. Sipariş yılı 1997 olan siparişleri alan çalışanları sipariş alma sayılarına göre sıralayınız.
%sql SELECT COUNT(*) n, em.FirstName FROM Orders LEFT JOIN Employees em on Orders.EmployeeID = em.EmployeeID WHERE OrderDate like '%1997%' GROUP BY em.FirstName ORDER by n DESC;

 * sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.db
   sqlite:///C:\Users\Zeynep\OneDrive\Belgeler\veri_tabanı-sqlite.sqbpro
Done.

[(13, 'Janet'),
 (9, 'Margaret'),
 (8, 'Laura'),
 (4, 'Andrew'),
 (3, 'Robert'),
 (3, 'Nancy'),
 (3, 'Michael'),
 (1, 'Anne')]